package fleming.david.com.quickkrtschedules;

import java.util.ArrayList;

public class Rt1WCData {

    protected String[] getTimes(String mDay, String mDirection, String mTimepoint) {

        ArrayList<String> mTimesList = new ArrayList<>();

        switch (mDay) {
            case "Monday-Friday":
                switch (mDirection) {
                    case "Outbound":
                        switch (mTimepoint) {
                            case "Laidley Transit Mall":
                                mTimesList.add("5:45 a.m.");
                                mTimesList.add("6:00 a.m.");
                                mTimesList.add("6:30 a.m.");
                                mTimesList.add("6:45 a.m.");
                                mTimesList.add("7:00 a.m.");
                                mTimesList.add("7:15 a.m.");
                                mTimesList.add("7:30 a.m.");
                                mTimesList.add("7:45 a.m.");
                                mTimesList.add("8:00 a.m.");
                                mTimesList.add("8:15 a.m.");
                                mTimesList.add("8:30 a.m.");
                                mTimesList.add("8:45 a.m.");
                                mTimesList.add("9:00 a.m.");
                                mTimesList.add("9:15 a.m.");
                                mTimesList.add("9:30 a.m.");
                                mTimesList.add("9:45 a.m.");
                                mTimesList.add("10:00 a.m.");
                                mTimesList.add("10:15 a.m.");
                                mTimesList.add("10:30 a.m.");
                                mTimesList.add("10:45 a.m.");
                                mTimesList.add("11:00 a.m.");
                                mTimesList.add("11:15 a.m.");
                                mTimesList.add("11:30 a.m.");
                                mTimesList.add("11:55 a.m.");
                                mTimesList.add("12:00 p.m.");
                                mTimesList.add("12:15 p.m.");
                                mTimesList.add("12:30 p.m.");
                                mTimesList.add("12:45 p.m.");
                                mTimesList.add("1:00 p.m.");
                                mTimesList.add("1:15 p.m.");
                                mTimesList.add("1:30 p.m.");
                                mTimesList.add("1:55 p.m.");
                                mTimesList.add("2:00 p.m.");
                                mTimesList.add("2:15 p.m.");
                                mTimesList.add("2:30 p.m.");
                                mTimesList.add("2:55 p.m.");
                                mTimesList.add("3:00 p.m.");
                                mTimesList.add("3:15 p.m.");
                                mTimesList.add("3:30 p.m.");
                                mTimesList.add("4:00 p.m.");
                                mTimesList.add("4:15 p.m.");
                                mTimesList.add("4:30 p.m.");
                                mTimesList.add("4:45 p.m.");
                                mTimesList.add("5:00 p.m.");
                                mTimesList.add("5:15 p.m.");
                                mTimesList.add("5:45 p.m.");
                                mTimesList.add("6:00 p.m.");
                                mTimesList.add("6:15 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("7:00 p.m.");
                                mTimesList.add("7:15 p.m.");
                                mTimesList.add("7:45 p.m.");
                                mTimesList.add("8:15 p.m.");
                                mTimesList.add("9:00 p.m.");
                                mTimesList.add("9:20 p.m.");
                                mTimesList.add("11:15 p.m.");
                                break;
                            case "4th at Stockton":
                                mTimesList.add("5:57 a.m.");
                                mTimesList.add("6:12 a.m.");
                                mTimesList.add("6:42 a.m.");
                                mTimesList.add("6:57 a.m.");
                                mTimesList.add("7:12 a.m.");
                                mTimesList.add("7:27 a.m.");
                                mTimesList.add("7:42 a.m.");
                                mTimesList.add("7:57 a.m.");
                                mTimesList.add("8:12 a.m.");
                                mTimesList.add("8:27 a.m.");
                                mTimesList.add("8:42 a.m.");
                                mTimesList.add("8:57 a.m.");
                                mTimesList.add("9:12 a.m.");
                                mTimesList.add("9:27 a.m.");
                                mTimesList.add("9:42 a.m.");
                                mTimesList.add("9:57 a.m.");
                                mTimesList.add("10:12 a.m.");
                                mTimesList.add("10:27 a.m.");
                                mTimesList.add("10:42 a.m.");
                                mTimesList.add("10:57 a.m.");
                                mTimesList.add("11:12 a.m.");
                                mTimesList.add("11:27 a.m.");
                                mTimesList.add("11:42 a.m.");
                                mTimesList.add("12:07 p.m.");
                                mTimesList.add("12:12 p.m.");
                                mTimesList.add("12:27 p.m.");
                                mTimesList.add("12:42 p.m.");
                                mTimesList.add("12:57 p.m.");
                                mTimesList.add("1:12 p.m.");
                                mTimesList.add("1:27 p.m.");
                                mTimesList.add("1:42 p.m.");
                                mTimesList.add("2:07 p.m.");
                                mTimesList.add("2:12 p.m.");
                                mTimesList.add("2:27 p.m.");
                                mTimesList.add("2:42 p.m.");
                                mTimesList.add("3:07 p.m.");
                                mTimesList.add("3:12 p.m.");
                                mTimesList.add("3:27 p.m.");
                                mTimesList.add("3:42 p.m.");
                                mTimesList.add("4:12 p.m.");
                                mTimesList.add("4:27 p.m.");
                                mTimesList.add("4:42 p.m.");
                                mTimesList.add("4:57 p.m.");
                                mTimesList.add("5:12 p.m.");
                                mTimesList.add("5:27 p.m.");
                                mTimesList.add("5:57 p.m.");
                                mTimesList.add("6:12 p.m.");
                                mTimesList.add("6:27 p.m.");
                                mTimesList.add("6:57 p.m.");
                                mTimesList.add("7:12 p.m.");
                                mTimesList.add("7:27 p.m.");
                                mTimesList.add("7:55 p.m.");
                                mTimesList.add("8:25 p.m.");
                                mTimesList.add("9:10 p.m.");
                                mTimesList.add("9:32 p.m.");
                                mTimesList.add("11:27 p.m.");
                                break;
                            case "Patrick Street Plaza":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("7:00 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("7:30 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("8:00 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("8:30 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("9:00 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("9:30 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("10:00 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("10:30 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("11:00 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("11:30 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("12:10 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("12:30 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("1:00 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("1:30 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("2:10 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("2:30 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("3:10 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("3:30 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("4:30 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("7:00 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                        }
                        break;
                    case "Inbound":
                        switch (mTimepoint) {
                            case "Patrick Street Plaza":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("5:30 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("6:45 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("7:15 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("7:45 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("8:15 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("8:45 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("9:15 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("9:45 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("10:15 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("10:45 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("11:15 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("11:45 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("12:15 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("12:45 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("1:15 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("1:45 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("2:15 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("2:45 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("3:15 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("3:45 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("4:45 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("5:00 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("6:35 p.m.");
                                mTimesList.add("7:00 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("8:55 p.m.");
                                mTimesList.add("-");
                                break;
                            case "4th at Stockton":
                                mTimesList.add("4:20 a.m.");
                                mTimesList.add("5:20 a.m.");
                                mTimesList.add("5:33 a.m.");
                                mTimesList.add("5:43 a.m.");
                                mTimesList.add("6:05 a.m.");
                                mTimesList.add("6:18 a.m.");
                                mTimesList.add("6:20 a.m.");
                                mTimesList.add("6:33 a.m.");
                                mTimesList.add("6:48 a.m.");
                                mTimesList.add("7:03 a.m.");
                                mTimesList.add("7:18 a.m.");
                                mTimesList.add("7:33 a.m.");
                                mTimesList.add("7:48 a.m.");
                                mTimesList.add("8:03 a.m.");
                                mTimesList.add("8:18 a.m.");
                                mTimesList.add("8:33 a.m.");
                                mTimesList.add("8:48 a.m.");
                                mTimesList.add("9:03 a.m.");
                                mTimesList.add("9:18 a.m.");
                                mTimesList.add("9:33 a.m.");
                                mTimesList.add("9:48 a.m.");
                                mTimesList.add("10:03 a.m.");
                                mTimesList.add("10:18 a.m.");
                                mTimesList.add("10:33 a.m.");
                                mTimesList.add("10:48 a.m.");
                                mTimesList.add("11:03 a.m.");
                                mTimesList.add("11:18 a.m.");
                                mTimesList.add("11:33 a.m.");
                                mTimesList.add("11:48 a.m.");
                                mTimesList.add("12:03 p.m.");
                                mTimesList.add("12:18 p.m.");
                                mTimesList.add("12:33 p.m.");
                                mTimesList.add("12:48 p.m.");
                                mTimesList.add("1:03 p.m.");
                                mTimesList.add("1:18 p.m.");
                                mTimesList.add("1:33 p.m.");
                                mTimesList.add("1:48 p.m.");
                                mTimesList.add("2:03 p.m.");
                                mTimesList.add("2:18 p.m.");
                                mTimesList.add("2:33 p.m.");
                                mTimesList.add("2:48 p.m.");
                                mTimesList.add("3:03 p.m.");
                                mTimesList.add("3:18 p.m.");
                                mTimesList.add("3:33 p.m.");
                                mTimesList.add("3:48 p.m.");
                                mTimesList.add("4:03 p.m.");
                                mTimesList.add("4:33 p.m.");
                                mTimesList.add("4:48 p.m.");
                                mTimesList.add("5:00 p.m.");
                                mTimesList.add("5:03 p.m.");
                                mTimesList.add("5:33 p.m.");
                                mTimesList.add("6:03 p.m.");
                                mTimesList.add("6:33 p.m.");
                                mTimesList.add("6:38 p.m.");
                                mTimesList.add("7:03 p.m.");
                                mTimesList.add("7:18 p.m.");
                                mTimesList.add("8:58 p.m.");
                                mTimesList.add("11:03 p.m.");
                                break;
                            case "Laidley Transit Mall":
                                mTimesList.add("4:30 a.m.");
                                mTimesList.add("5:30 a.m.");
                                mTimesList.add("5:45 a.m.");
                                mTimesList.add("5:55 a.m.");
                                mTimesList.add("6:15 a.m.");
                                mTimesList.add("6:30 a.m.");
                                mTimesList.add("6:30 a.m.");
                                mTimesList.add("6:45 a.m.");
                                mTimesList.add("7:00 a.m.");
                                mTimesList.add("7:15 a.m.");
                                mTimesList.add("7:30 a.m.");
                                mTimesList.add("7:45 a.m.");
                                mTimesList.add("8:00 a.m.");
                                mTimesList.add("8:15 a.m.");
                                mTimesList.add("8:30 a.m.");
                                mTimesList.add("8:45 a.m.");
                                mTimesList.add("9:00 a.m.");
                                mTimesList.add("9:15 a.m.");
                                mTimesList.add("9:30 a.m.");
                                mTimesList.add("9:45 a.m.");
                                mTimesList.add("10:00 a.m.");
                                mTimesList.add("10:15 a.m.");
                                mTimesList.add("10:30 a.m.");
                                mTimesList.add("10:45 a.m.");
                                mTimesList.add("11:00 a.m.");
                                mTimesList.add("11:15 a.m.");
                                mTimesList.add("11:30 a.m.");
                                mTimesList.add("11:45 a.m.");
                                mTimesList.add("12:00 p.m.");
                                mTimesList.add("12:15 p.m.");
                                mTimesList.add("12:30 p.m.");
                                mTimesList.add("12:45 p.m.");
                                mTimesList.add("1:00 p.m.");
                                mTimesList.add("1:15 p.m.");
                                mTimesList.add("1:30 p.m.");
                                mTimesList.add("1:45 p.m.");
                                mTimesList.add("2:00 p.m.");
                                mTimesList.add("2:15 p.m.");
                                mTimesList.add("2:30 p.m.");
                                mTimesList.add("2:45 p.m.");
                                mTimesList.add("3:00 p.m.");
                                mTimesList.add("3:15 p.m.");
                                mTimesList.add("3:30 p.m.");
                                mTimesList.add("3:45 p.m.");
                                mTimesList.add("4:00 p.m.");
                                mTimesList.add("4:15 p.m.");
                                mTimesList.add("4:45 p.m.");
                                mTimesList.add("5:00 p.m.");
                                mTimesList.add("5:15 p.m.");
                                mTimesList.add("5:15 p.m.");
                                mTimesList.add("5:45 p.m.");
                                mTimesList.add("6:15 p.m.");
                                mTimesList.add("6:45 p.m.");
                                mTimesList.add("6:50 p.m.");
                                mTimesList.add("7:15 p.m.");
                                mTimesList.add("7:30 p.m.");
                                mTimesList.add("9:10 p.m.");
                                mTimesList.add("11:15 p.m.");
                                break;
                        }
                        break;
                }
                break;
            case "Saturday":
                switch (mDirection) {
                    case "Outbound":
                        switch (mTimepoint) {
                            case "Laidley Transit Mall":
                                mTimesList.add("6:00 a.m.");
                                mTimesList.add("6:30 a.m.");
                                mTimesList.add("7:00 a.m.");
                                mTimesList.add("7:30 a.m.");
                                mTimesList.add("8:00 a.m.");
                                mTimesList.add("8:30 a.m.");
                                mTimesList.add("9:00 a.m.");
                                mTimesList.add("9:30 a.m.");
                                mTimesList.add("10:00 a.m.");
                                mTimesList.add("10:30 a.m.");
                                mTimesList.add("11:00 a.m.");
                                mTimesList.add("11:30 a.m.");
                                mTimesList.add("12:00 p.m.");
                                mTimesList.add("12:30 p.m.");
                                mTimesList.add("1:00 p.m.");
                                mTimesList.add("1:30 p.m.");
                                mTimesList.add("2:00 p.m.");
                                mTimesList.add("2:30 p.m.");
                                mTimesList.add("3:00 p.m.");
                                mTimesList.add("3:30 p.m.");
                                mTimesList.add("4:00 p.m.");
                                mTimesList.add("4:30 p.m.");
                                mTimesList.add("5:00 p.m.");
                                mTimesList.add("5:30 p.m.");
                                mTimesList.add("6:00 p.m.");
                                mTimesList.add("6:30 p.m.");
                                mTimesList.add("7:15 p.m.");
                                mTimesList.add("7:30 p.m.");
                                mTimesList.add("9:20 p.m.");
                                mTimesList.add("11:15 p.m.");
                                break;
                            case "4th at Stockton":
                                mTimesList.add("6:13 a.m.");
                                mTimesList.add("6:43 a.m.");
                                mTimesList.add("7:13 a.m.");
                                mTimesList.add("7:43 a.m.");
                                mTimesList.add("8:13 a.m.");
                                mTimesList.add("8:43 a.m.");
                                mTimesList.add("9:13 a.m.");
                                mTimesList.add("9:43 a.m.");
                                mTimesList.add("10:13 a.m.");
                                mTimesList.add("10:43 a.m.");
                                mTimesList.add("11:13 a.m.");
                                mTimesList.add("11:43 a.m.");
                                mTimesList.add("12:13 p.m.");
                                mTimesList.add("12:43 p.m.");
                                mTimesList.add("1:13 p.m.");
                                mTimesList.add("1:43 p.m.");
                                mTimesList.add("2:13 p.m.");
                                mTimesList.add("2:43 p.m.");
                                mTimesList.add("3:13 p.m.");
                                mTimesList.add("3:43 p.m.");
                                mTimesList.add("4:13 p.m.");
                                mTimesList.add("4:43 p.m.");
                                mTimesList.add("5:13 p.m.");
                                mTimesList.add("5:43 p.m.");
                                mTimesList.add("6:13 p.m.");
                                mTimesList.add("6:43 p.m.");
                                mTimesList.add("7:28 p.m.");
                                mTimesList.add("7:43 p.m.");
                                mTimesList.add("9:32 p.m.");
                                mTimesList.add("11:28 p.m.");
                                break;
                            case "Patrick Street Plaza":
                                mTimesList.add("-");
                                mTimesList.add("6:47 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("7:47 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("8:47 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("9:47 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("10:47 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("11:47 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("12:47 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("1:47 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("2:47 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("3:47 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("4:47 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("5:47 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("7:47 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                        }
                        break;
                    case "Inbound":
                        switch (mTimepoint) {
                            case "Patrick Street Plaza":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("7:03 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("8:03 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("9:03 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("10:03 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("11:03 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("12:03 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("1:03 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("2:03 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("3:03 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("4:03 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("5:03 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("6:03 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("7:47 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                            case "4th at Stockton":
                                mTimesList.add("5:20 a.m.");
                                mTimesList.add("5:50 a.m.");
                                mTimesList.add("6:47 a.m.");
                                mTimesList.add("7:07 a.m.");
                                mTimesList.add("7:47 a.m.");
                                mTimesList.add("8:07 a.m.");
                                mTimesList.add("8:47 a.m.");
                                mTimesList.add("9:07 a.m.");
                                mTimesList.add("9:47 a.m.");
                                mTimesList.add("10:07 a.m.");
                                mTimesList.add("10:47 a.m.");
                                mTimesList.add("11:07 a.m.");
                                mTimesList.add("11:47 a.m.");
                                mTimesList.add("12:07 p.m.");
                                mTimesList.add("12:47 p.m.");
                                mTimesList.add("1:07 p.m.");
                                mTimesList.add("1:47 p.m.");
                                mTimesList.add("2:07 p.m.");
                                mTimesList.add("2:47 p.m.");
                                mTimesList.add("3:07 p.m.");
                                mTimesList.add("3:47 p.m.");
                                mTimesList.add("4:07 p.m.");
                                mTimesList.add("4:47 p.m.");
                                mTimesList.add("5:07 p.m.");
                                mTimesList.add("5:47 p.m.");
                                mTimesList.add("6:07 p.m.");
                                mTimesList.add("6:47 p.m.");
                                mTimesList.add("7:47 p.m.");
                                mTimesList.add("7:50 p.m.");
                                mTimesList.add("9:02 p.m.");
                                mTimesList.add("11:03 p.m.");
                                break;
                            case "Laidley Transit Mall":
                                mTimesList.add("5:30 a.m.");
                                mTimesList.add("6:00 a.m.");
                                mTimesList.add("7:00 a.m.");
                                mTimesList.add("7:20 a.m.");
                                mTimesList.add("8:00 a.m.");
                                mTimesList.add("8:20 a.m.");
                                mTimesList.add("9:00 a.m.");
                                mTimesList.add("9:20 a.m.");
                                mTimesList.add("10:00 a.m.");
                                mTimesList.add("10:20 a.m.");
                                mTimesList.add("11:00 a.m.");
                                mTimesList.add("11:20 a.m.");
                                mTimesList.add("12:00 p.m.");
                                mTimesList.add("12:20 p.m.");
                                mTimesList.add("1:00 p.m.");
                                mTimesList.add("1:20 p.m.");
                                mTimesList.add("2:00 p.m.");
                                mTimesList.add("2:20 p.m.");
                                mTimesList.add("3:00 p.m.");
                                mTimesList.add("3:20 p.m.");
                                mTimesList.add("4:00 p.m.");
                                mTimesList.add("4:20 p.m.");
                                mTimesList.add("5:00 p.m.");
                                mTimesList.add("5:20 p.m.");
                                mTimesList.add("6:00 p.m.");
                                mTimesList.add("6:20 p.m.");
                                mTimesList.add("7:00 p.m.");
                                mTimesList.add("8:00 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("9:15 p.m.");
                                mTimesList.add("11:15 p.m.");
                                break;
                        }
                        break;
                }
                break;
            case "Sunday":
                switch (mDirection) {
                    case "Outbound":
                        switch (mTimepoint) {
                            case "Laidley Transit Mall":
                                mTimesList.add("-");
                                mTimesList.add("7:15 a.m.");
                                mTimesList.add("9:15 a.m.");
                                mTimesList.add("11:15 a.m.");
                                mTimesList.add("1:15 p.m.");
                                mTimesList.add("3:15 p.m.");
                                mTimesList.add("5:15 p.m.");
                                mTimesList.add("7:15 p.m.");
                                mTimesList.add("9:15 p.m.");
                                mTimesList.add("11:15 p.m.");
                                break;
                            case "4th at Stockton":
                                mTimesList.add("5:28 a.m.");
                                mTimesList.add("7:28 a.m.");
                                mTimesList.add("9:28 a.m.");
                                mTimesList.add("11:28 a.m.");
                                mTimesList.add("1:28 p.m.");
                                mTimesList.add("3:28 p.m.");
                                mTimesList.add("5:28 p.m.");
                                mTimesList.add("7:28 p.m.");
                                mTimesList.add("9:28 p.m.");
                                mTimesList.add("11:28 p.m.");
                                break;
                            case "Patrick Street Plaza":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                        }
                        break;
                    case "Inbound":
                        switch (mTimepoint) {
                            case "Patrick Street Plaza":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                            case "4th at Stockton":
                                mTimesList.add("5:05 a.m.");
                                mTimesList.add("7:02 a.m.");
                                mTimesList.add("9:02 a.m.");
                                mTimesList.add("11:02 a.m.");
                                mTimesList.add("1:02 p.m.");
                                mTimesList.add("3:02 p.m.");
                                mTimesList.add("5:02 p.m.");
                                mTimesList.add("7:02 p.m.");
                                mTimesList.add("9:02 p.m.");
                                mTimesList.add("11:02 p.m.");
                                mTimesList.add("12:47 p.m.");
                                break;
                            case "Laidley Transit Mall":
                                mTimesList.add("5:15 a.m.");
                                mTimesList.add("7:15 a.m.");
                                mTimesList.add("9:15 a.m.");
                                mTimesList.add("11:15 a.m.");
                                mTimesList.add("1:15 p.m.");
                                mTimesList.add("3:15 p.m.");
                                mTimesList.add("5:15 p.m.");
                                mTimesList.add("7:15 p.m.");
                                mTimesList.add("9:15 p.m.");
                                mTimesList.add("11:15 p.m.");
                                mTimesList.add("-");
                                break;
                        }
                        break;
                }
                break;
        }

        String[] mTimes = new String[mTimesList.size()];

        for (int i = 0; i < mTimes.length; i++)
            mTimes[i] = mTimesList.get(i);

        return mTimes;
    }

}
