package fleming.david.com.quickkrtschedules;

import java.util.ArrayList;

public class Rt3NData {

    protected String[] getTimes(String mDay, String mDirection, String mTimepoint) {

        ArrayList<String> mTimesList = new ArrayList<>();

        switch (mDay) {
            case "Monday-Friday":
                switch (mDirection) {
                    case "Outbound":
                        switch (mTimepoint) {
                            case "Capitol Complex":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("6:59 a.m.");
                                mTimesList.add("7:59 a.m.");
                                mTimesList.add("8:59 a.m.");
                                mTimesList.add("9:59 a.m.");
                                mTimesList.add("10:59 a.m.");
                                mTimesList.add("11:59 a.m.");
                                mTimesList.add("1:09 p.m.");
                                mTimesList.add("2:09 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("4:09 p.m.");
                                mTimesList.add("5:09 p.m.");
                                mTimesList.add("6:09 p.m.");
                                mTimesList.add("7:09 p.m.");
                                mTimesList.add("8:09 p.m.");
                                mTimesList.add("9:09 p.m.");
                                mTimesList.add("-");
                                break;
                            case "Laidley Transit Mall":
                                mTimesList.add("-");
                                mTimesList.add("5:20 a.m.");
                                mTimesList.add("6:20 a.m.");
                                mTimesList.add("7:10 a.m.");
                                mTimesList.add("8:10 a.m.");
                                mTimesList.add("9:10 a.m.");
                                mTimesList.add("10:10 a.m.");
                                mTimesList.add("11:10 a.m.");
                                mTimesList.add("12:10 p.m.");
                                mTimesList.add("1:20 p.m.");
                                mTimesList.add("2:20 p.m.");
                                mTimesList.add("3:20 p.m.");
                                mTimesList.add("4:20 p.m.");
                                mTimesList.add("5:20 p.m.");
                                mTimesList.add("6:20 p.m.");
                                mTimesList.add("7:20 p.m.");
                                mTimesList.add("8:20 p.m.");
                                mTimesList.add("9:20 p.m.");
                                mTimesList.add("11:15 p.m.");
                                break;
                            case "7th Ave and 26th St":
                                mTimesList.add("5:05 a.m.");
                                mTimesList.add("5:34 a.m.");
                                mTimesList.add("6:34 a.m.");
                                mTimesList.add("7:24 a.m.");
                                mTimesList.add("8:24 a.m.");
                                mTimesList.add("9:24 a.m.");
                                mTimesList.add("10:24 a.m.");
                                mTimesList.add("11:24 a.m.");
                                mTimesList.add("12:24 p.m.");
                                mTimesList.add("1:34 p.m.");
                                mTimesList.add("2:34 p.m.");
                                mTimesList.add("3:34 p.m.");
                                mTimesList.add("4:34 p.m.");
                                mTimesList.add("5:34 p.m.");
                                mTimesList.add("6:34 p.m.");
                                mTimesList.add("7:34 p.m.");
                                mTimesList.add("8:34 p.m.");
                                mTimesList.add("9:34 p.m.");
                                mTimesList.add("11:34 p.m.");
                                break;
                            case "12th and Dunbar Ave":
                                mTimesList.add("5:14 a.m.");
                                mTimesList.add("5:43 a.m.");
                                mTimesList.add("6:43 a.m.");
                                mTimesList.add("7:33 a.m.");
                                mTimesList.add("8:33 a.m.");
                                mTimesList.add("9:33 a.m.");
                                mTimesList.add("10:33 a.m.");
                                mTimesList.add("11:33 a.m.");
                                mTimesList.add("12:33 p.m.");
                                mTimesList.add("1:43 p.m.");
                                mTimesList.add("2:43 p.m.");
                                mTimesList.add("3:43 p.m.");
                                mTimesList.add("4:43 p.m.");
                                mTimesList.add("5:43 p.m.");
                                mTimesList.add("6:43 p.m.");
                                mTimesList.add("7:43 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("9:43 p.m.");
                                mTimesList.add("11:43 p.m.");
                                break;
                            case "WV State University":
                                mTimesList.add("5:22 a.m.");
                                mTimesList.add("5:51 a.m.");
                                mTimesList.add("6:51 a.m.");
                                mTimesList.add("7:41 a.m.");
                                mTimesList.add("8:41 a.m.");
                                mTimesList.add("9:41 a.m.");
                                mTimesList.add("10:41 a.m.");
                                mTimesList.add("11:41 a.m.");
                                mTimesList.add("12:41 p.m.");
                                mTimesList.add("1:51 p.m.");
                                mTimesList.add("2:51 p.m.");
                                mTimesList.add("3:51 p.m.");
                                mTimesList.add("4:51 p.m.");
                                mTimesList.add("5:51 p.m.");
                                mTimesList.add("6:51 p.m.");
                                mTimesList.add("7:51 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("9:51 p.m.");
                                mTimesList.add("11:51 p.m.");
                                break;
                            case "St Albans Station":
                                mTimesList.add("-");
                                mTimesList.add("6:04 a.m.");
                                mTimesList.add("7:04 a.m.");
                                mTimesList.add("7:54 a.m.");
                                mTimesList.add("8:54 a.m.");
                                mTimesList.add("9:54 a.m.");
                                mTimesList.add("10:54 a.m.");
                                mTimesList.add("11:54 a.m.");
                                mTimesList.add("12:54 p.m.");
                                mTimesList.add("2:04 p.m.");
                                mTimesList.add("3:04 p.m.");
                                mTimesList.add("4:04 p.m.");
                                mTimesList.add("5:04 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("7:04 p.m.");
                                mTimesList.add("8:04 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("12:04 a.m.");
                                break;
                            case "40th St and Route 25":
                                mTimesList.add("5:32 a.m.");
                                mTimesList.add("6:17 a.m.");
                                mTimesList.add("7:17 a.m.");
                                mTimesList.add("8:07 a.m.");
                                mTimesList.add("9:07 a.m.");
                                mTimesList.add("10:07 a.m.");
                                mTimesList.add("11:07 a.m.");
                                mTimesList.add("12:07 p.m.");
                                mTimesList.add("1:07 p.m.");
                                mTimesList.add("2:17 p.m.");
                                mTimesList.add("3:17 p.m.");
                                mTimesList.add("4:17 p.m.");
                                mTimesList.add("5:17 p.m.");
                                mTimesList.add("6:04 p.m.");
                                mTimesList.add("7:17 p.m.");
                                mTimesList.add("8:17 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("10:01 p.m.");
                                mTimesList.add("12:17 a.m.");
                                break;
                            case "Nitro Marketplace":
                                mTimesList.add("5:42 a.m.");
                                mTimesList.add("6:27 a.m.");
                                mTimesList.add("7:27 a.m.");
                                mTimesList.add("8:17 a.m.");
                                mTimesList.add("9:17 a.m.");
                                mTimesList.add("10:17 a.m.");
                                mTimesList.add("11:17 a.m.");
                                mTimesList.add("12:17 p.m.");
                                mTimesList.add("1:17 p.m.");
                                mTimesList.add("2:27 p.m.");
                                mTimesList.add("3:27 p.m.");
                                mTimesList.add("4:27 p.m.");
                                mTimesList.add("5:27 p.m.");
                                mTimesList.add("6:15 p.m.");
                                mTimesList.add("7:27 p.m.");
                                mTimesList.add("8:27 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("10:11 p.m.");
                                mTimesList.add("12:27 a.m.");
                                break;
                            case "Mardi Gras Casino & Resort":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("8:20 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("10:20 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("2:30 p.m.");
                                mTimesList.add("3:30 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("5:30 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("12:30 a.m.");
                                break;
                        }
                        break;
                    case "Inbound":
                        switch (mTimepoint) {
                            case "Mardi Gras Casino & Resort":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("8:31 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("10:31 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("2:41 p.m.");
                                mTimesList.add("3:41 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("5:41 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("12:30 a.m.");
                                break;
                            case "Nitro Marketplace":
                                mTimesList.add("5:44 a.m.");
                                mTimesList.add("6:30 a.m.");
                                mTimesList.add("7:34 a.m.");
                                mTimesList.add("8:34 a.m.");
                                mTimesList.add("9:34 a.m.");
                                mTimesList.add("10:34 a.m.");
                                mTimesList.add("11:44 a.m.");
                                mTimesList.add("12:21 p.m.");
                                mTimesList.add("1:44 p.m.");
                                mTimesList.add("2:44 p.m.");
                                mTimesList.add("3:44 p.m.");
                                mTimesList.add("4:44 p.m.");
                                mTimesList.add("5:44 p.m.");
                                mTimesList.add("6:44 p.m.");
                                mTimesList.add("7:44 p.m.");
                                mTimesList.add("8:44 p.m.");
                                mTimesList.add("10:15 p.m.");
                                mTimesList.add("-");
                                break;
                            case "40th St and Route 25":
                                mTimesList.add("5:54 a.m.");
                                mTimesList.add("6:42 a.m.");
                                mTimesList.add("7:44 a.m.");
                                mTimesList.add("8:44 a.m.");
                                mTimesList.add("9:44 a.m.");
                                mTimesList.add("10:44 a.m.");
                                mTimesList.add("11:54 a.m.");
                                mTimesList.add("12:31 p.m.");
                                mTimesList.add("1:54 p.m.");
                                mTimesList.add("2:54 p.m.");
                                mTimesList.add("3:54 p.m.");
                                mTimesList.add("4:54 p.m.");
                                mTimesList.add("5:54 p.m.");
                                mTimesList.add("6:54 p.m.");
                                mTimesList.add("7:54 p.m.");
                                mTimesList.add("8:54 p.m.");
                                mTimesList.add("10:25 p.m.");
                                mTimesList.add("12:40 a.m.");
                                break;
                            case "St Albans Station":
                                mTimesList.add("-");
                                mTimesList.add("6:57 a.m.");
                                mTimesList.add("7:57 a.m.");
                                mTimesList.add("8:57 a.m.");
                                mTimesList.add("9:57 a.m.");
                                mTimesList.add("10:57 a.m.");
                                mTimesList.add("12:07 p.m.");
                                mTimesList.add("12:44 p.m.");
                                mTimesList.add("2:07 p.m.");
                                mTimesList.add("3:07 p.m.");
                                mTimesList.add("4:07 p.m.");
                                mTimesList.add("5:07 p.m.");
                                mTimesList.add("6:07 p.m.");
                                mTimesList.add("7:07 p.m.");
                                mTimesList.add("8:07 p.m.");
                                mTimesList.add("9:07 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                            case "WV State University":
                                mTimesList.add("6:04 a.m.");
                                mTimesList.add("7:10 a.m.");
                                mTimesList.add("8:10 a.m.");
                                mTimesList.add("9:10 a.m.");
                                mTimesList.add("10:10 a.m.");
                                mTimesList.add("11:10 a.m.");
                                mTimesList.add("12:20 p.m.");
                                mTimesList.add("12:57 p.m.");
                                mTimesList.add("2:20 p.m.");
                                mTimesList.add("3:20 p.m.");
                                mTimesList.add("4:20 p.m.");
                                mTimesList.add("5:20 p.m.");
                                mTimesList.add("6:20 p.m.");
                                mTimesList.add("7:20 p.m.");
                                mTimesList.add("8:20 p.m.");
                                mTimesList.add("9:20 p.m.");
                                mTimesList.add("10:35 p.m.");
                                mTimesList.add("12:50 a.m.");
                                break;
                            case "12th and Dunbar Ave":
                                mTimesList.add("6:12 a.m.");
                                mTimesList.add("7:18 a.m.");
                                mTimesList.add("8:18 a.m.");
                                mTimesList.add("9:18 a.m.");
                                mTimesList.add("10:18 a.m.");
                                mTimesList.add("11:18 a.m.");
                                mTimesList.add("12:28 p.m.");
                                mTimesList.add("1:05 p.m.");
                                mTimesList.add("2:28 p.m.");
                                mTimesList.add("3:28 p.m.");
                                mTimesList.add("4:28 p.m.");
                                mTimesList.add("5:28 p.m.");
                                mTimesList.add("6:28 p.m.");
                                mTimesList.add("7:28 p.m.");
                                mTimesList.add("8:28 p.m.");
                                mTimesList.add("9:28 p.m.");
                                mTimesList.add("10:43 p.m.");
                                mTimesList.add("12:57 a.m.");
                                break;
                            case "7th Ave and 26th St":
                                mTimesList.add("6:22 a.m.");
                                mTimesList.add("7:28 a.m.");
                                mTimesList.add("8:28 a.m.");
                                mTimesList.add("9:28 a.m.");
                                mTimesList.add("10:28 a.m.");
                                mTimesList.add("11:28 a.m.");
                                mTimesList.add("12:38 p.m.");
                                mTimesList.add("1:15 p.m.");
                                mTimesList.add("2:38 p.m.");
                                mTimesList.add("3:38 p.m.");
                                mTimesList.add("4:38 p.m.");
                                mTimesList.add("5:38 p.m.");
                                mTimesList.add("6:38 p.m.");
                                mTimesList.add("7:38 p.m.");
                                mTimesList.add("8:38 p.m.");
                                mTimesList.add("9:38 p.m.");
                                mTimesList.add("10:51 p.m.");
                                mTimesList.add("1:05 a.m.");
                                break;
                            case "Laidley Transit Mall":
                                mTimesList.add("6:39 a.m.");
                                mTimesList.add("7:45 a.m.");
                                mTimesList.add("8:45 a.m.");
                                mTimesList.add("9:45 a.m.");
                                mTimesList.add("10:45 a.m.");
                                mTimesList.add("11:45 a.m.");
                                mTimesList.add("12:55 p.m.");
                                mTimesList.add("1:32 p.m.");
                                mTimesList.add("2:55 p.m.");
                                mTimesList.add("3:55 p.m.");
                                mTimesList.add("4:55 p.m.");
                                mTimesList.add("5:55 p.m.");
                                mTimesList.add("6:55 p.m.");
                                mTimesList.add("7:55 p.m.");
                                mTimesList.add("8:55 p.m.");
                                mTimesList.add("9:55 p.m.");
                                mTimesList.add("11:08 p.m.");
                                mTimesList.add("-");
                                break;
                            case "Capitol Complex":
                                mTimesList.add("6:51 a.m.");
                                mTimesList.add("7:57 a.m.");
                                mTimesList.add("8:57 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("10:57 a.m.");
                                mTimesList.add("11:57 a.m.");
                                mTimesList.add("1:07 p.m.");
                                mTimesList.add("1:44 p.m.");
                                mTimesList.add("3:07 p.m.");
                                mTimesList.add("4:07 p.m.");
                                mTimesList.add("5:07 p.m.");
                                mTimesList.add("6:07 p.m.");
                                mTimesList.add("7:07 p.m.");
                                mTimesList.add("8:07 p.m.");
                                mTimesList.add("9:07 p.m.");
                                mTimesList.add("10:07 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                        }
                        break;
                }
                break;
            case "Saturday":
                switch (mDirection) {
                    case "Outbound":
                        switch (mTimepoint) {
                            case "Capitol Complex":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                            case "Laidley Transit Mall":
                                mTimesList.add("-");
                                mTimesList.add("5:30 a.m.");
                                mTimesList.add("6:30 a.m.");
                                mTimesList.add("7:30 a.m.");
                                mTimesList.add("8:30 a.m.");
                                mTimesList.add("9:30 a.m.");
                                mTimesList.add("10:30 a.m.");
                                mTimesList.add("11:30 a.m.");
                                mTimesList.add("12:30 p.m.");
                                mTimesList.add("1:30 p.m.");
                                mTimesList.add("2:30 p.m.");
                                mTimesList.add("2:45 p.m.");
                                mTimesList.add("3:30 p.m.");
                                mTimesList.add("4:30 p.m.");
                                mTimesList.add("5:30 p.m.");
                                mTimesList.add("6:45 p.m.");
                                mTimesList.add("7:15 p.m.");
                                mTimesList.add("9:20 p.m.");
                                mTimesList.add("11:15 p.m.");
                                break;
                            case "7th Ave and 26th St":
                                mTimesList.add("5:20 a.m.");
                                mTimesList.add("5:48 a.m.");
                                mTimesList.add("6:48 a.m.");
                                mTimesList.add("7:48 a.m.");
                                mTimesList.add("8:48 a.m.");
                                mTimesList.add("9:48 a.m.");
                                mTimesList.add("10:48 a.m.");
                                mTimesList.add("11:48 a.m.");
                                mTimesList.add("12:48 p.m.");
                                mTimesList.add("1:48 p.m.");
                                mTimesList.add("2:48 p.m.");
                                mTimesList.add("2:58 p.m.");
                                mTimesList.add("3:48 p.m.");
                                mTimesList.add("4:48 p.m.");
                                mTimesList.add("5:48 p.m.");
                                mTimesList.add("6:58 p.m.");
                                mTimesList.add("7:29 p.m.");
                                mTimesList.add("9:34 p.m.");
                                mTimesList.add("11:29 p.m.");
                                break;
                            case "12th and Dunbar Ave":
                                mTimesList.add("5:27 a.m.");
                                mTimesList.add("5:56 a.m.");
                                mTimesList.add("6:56 a.m.");
                                mTimesList.add("7:56 a.m.");
                                mTimesList.add("8:56 a.m.");
                                mTimesList.add("9:56 a.m.");
                                mTimesList.add("10:56 a.m.");
                                mTimesList.add("11:56 a.m.");
                                mTimesList.add("12:56 p.m.");
                                mTimesList.add("1:56 p.m.");
                                mTimesList.add("2:56 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("3:56 p.m.");
                                mTimesList.add("4:56 p.m.");
                                mTimesList.add("5:56 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("7:35 p.m.");
                                mTimesList.add("9:43 p.m.");
                                mTimesList.add("11:35 p.m.");
                                break;
                            case "WV State University":
                                mTimesList.add("5:35 a.m.");
                                mTimesList.add("6:05 a.m.");
                                mTimesList.add("7:05 a.m.");
                                mTimesList.add("8:05 a.m.");
                                mTimesList.add("9:05 a.m.");
                                mTimesList.add("10:05 a.m.");
                                mTimesList.add("11:05 a.m.");
                                mTimesList.add("12:05 p.m.");
                                mTimesList.add("1:05 p.m.");
                                mTimesList.add("2:05 p.m.");
                                mTimesList.add("3:05 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("4:05 p.m.");
                                mTimesList.add("5:05 p.m.");
                                mTimesList.add("6:05 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("7:41 p.m.");
                                mTimesList.add("9:51 p.m.");
                                mTimesList.add("11:41 p.m.");
                                break;
                            case "St Albans Station":
                                mTimesList.add("-");
                                mTimesList.add("6:15 a.m.");
                                mTimesList.add("7:15 a.m.");
                                mTimesList.add("8:15 a.m.");
                                mTimesList.add("9:15 a.m.");
                                mTimesList.add("10:15 a.m.");
                                mTimesList.add("11:15 a.m.");
                                mTimesList.add("12:15 p.m.");
                                mTimesList.add("1:15 p.m.");
                                mTimesList.add("2:15 p.m.");
                                mTimesList.add("3:15 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("4:15 p.m.");
                                mTimesList.add("5:15 p.m.");
                                mTimesList.add("6:15 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                            case "40th St and Route 25":
                                mTimesList.add("5:45 a.m.");
                                mTimesList.add("6:30 a.m.");
                                mTimesList.add("7:30 a.m.");
                                mTimesList.add("8:30 a.m.");
                                mTimesList.add("9:30 a.m.");
                                mTimesList.add("10:30 a.m.");
                                mTimesList.add("11:30 a.m.");
                                mTimesList.add("12:30 p.m.");
                                mTimesList.add("1:30 p.m.");
                                mTimesList.add("2:30 p.m.");
                                mTimesList.add("3:30 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("4:30 p.m.");
                                mTimesList.add("5:30 p.m.");
                                mTimesList.add("6:30 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("7:53 p.m.");
                                mTimesList.add("10:01 p.m.");
                                mTimesList.add("11:53 p.m.");
                                break;
                            case "Nitro Marketplace":
                                mTimesList.add("5:55 a.m.");
                                mTimesList.add("6:40 a.m.");
                                mTimesList.add("7:40 a.m.");
                                mTimesList.add("8:40 a.m.");
                                mTimesList.add("9:40 a.m.");
                                mTimesList.add("10:40 a.m.");
                                mTimesList.add("11:40 a.m.");
                                mTimesList.add("12:40 p.m.");
                                mTimesList.add("1:40 p.m.");
                                mTimesList.add("2:40 p.m.");
                                mTimesList.add("3:40 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("4:40 p.m.");
                                mTimesList.add("5:40 p.m.");
                                mTimesList.add("6:40 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("8:03 p.m.");
                                mTimesList.add("10:11 p.m.");
                                mTimesList.add("12:03 a.m.");
                                break;
                            case "Mardi Gras Casino & Resort":
                                mTimesList.add("5:58 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("8:06 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("12:05 a.m.");
                                break;
                        }
                        break;
                    case "Inbound":
                        switch (mTimepoint) {
                            case "Mardi Gras Casino & Resort":
                                mTimesList.add("5:58 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("8:24 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("12:0 a.m.");
                                break;
                            case "Nitro Marketplace":
                                mTimesList.add("6:01 a.m.");
                                mTimesList.add("6:47 a.m.");
                                mTimesList.add("7:47 a.m.");
                                mTimesList.add("8:47 a.m.");
                                mTimesList.add("9:47 a.m.");
                                mTimesList.add("10:47 a.m.");
                                mTimesList.add("11:47 a.m.");
                                mTimesList.add("12:47 p.m.");
                                mTimesList.add("1:47 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("2:47 p.m.");
                                mTimesList.add("3:47 p.m.");
                                mTimesList.add("4:47 p.m.");
                                mTimesList.add("5:47 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("6:47 p.m.");
                                mTimesList.add("8:27 p.m.");
                                mTimesList.add("10:15 p.m.");
                                mTimesList.add("-");
                                break;
                            case "40th St and Route 25":
                                mTimesList.add("6:11 a.m.");
                                mTimesList.add("6:57 a.m.");
                                mTimesList.add("7:57 a.m.");
                                mTimesList.add("8:57 a.m.");
                                mTimesList.add("9:57 a.m.");
                                mTimesList.add("10:57 a.m.");
                                mTimesList.add("11:57 a.m.");
                                mTimesList.add("12:57 p.m.");
                                mTimesList.add("1:57 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("2:57 p.m.");
                                mTimesList.add("3:57 p.m.");
                                mTimesList.add("4:57 p.m.");
                                mTimesList.add("5:57 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("6:57 p.m.");
                                mTimesList.add("8:37 p.m.");
                                mTimesList.add("10:25 p.m.");
                                mTimesList.add("12:15 a.m.");
                                break;
                            case "St Albans Station":
                                mTimesList.add("-");
                                mTimesList.add("7:12 a.m.");
                                mTimesList.add("8:12 a.m.");
                                mTimesList.add("9:12 a.m.");
                                mTimesList.add("10:12 a.m.");
                                mTimesList.add("11:12 a.m.");
                                mTimesList.add("12:12 p.m.");
                                mTimesList.add("1:12 p.m.");
                                mTimesList.add("2:12 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("3:12 p.m.");
                                mTimesList.add("4:12 p.m.");
                                mTimesList.add("5:12 p.m.");
                                mTimesList.add("6:12 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("7:12 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("10:38 p.m.");
                                mTimesList.add("-");
                                break;
                            case "WV State University":
                                mTimesList.add("6:26 a.m.");
                                mTimesList.add("7:22 a.m.");
                                mTimesList.add("8:22 a.m.");
                                mTimesList.add("9:22 a.m.");
                                mTimesList.add("10:22 a.m.");
                                mTimesList.add("11:22 a.m.");
                                mTimesList.add("12:22 p.m.");
                                mTimesList.add("1:22 p.m.");
                                mTimesList.add("2:22 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("3:22 p.m.");
                                mTimesList.add("4:22 p.m.");
                                mTimesList.add("5:22 p.m.");
                                mTimesList.add("6:22 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("7:22 p.m.");
                                mTimesList.add("8:49 p.m.");
                                mTimesList.add("10:50 p.m.");
                                mTimesList.add("12:25 a.m.");
                                break;
                            case "12th and Dunbar Ave":
                                mTimesList.add("6:34 a.m.");
                                mTimesList.add("7:30 a.m.");
                                mTimesList.add("8:30 a.m.");
                                mTimesList.add("9:30 a.m.");
                                mTimesList.add("10:30 a.m.");
                                mTimesList.add("11:30 a.m.");
                                mTimesList.add("12:30 p.m.");
                                mTimesList.add("1:30 p.m.");
                                mTimesList.add("2:30 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("3:30 p.m.");
                                mTimesList.add("4:30 p.m.");
                                mTimesList.add("5:30 p.m.");
                                mTimesList.add("6:30 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("7:30 p.m.");
                                mTimesList.add("8:55 p.m.");
                                mTimesList.add("10:56 p.m.");
                                mTimesList.add("12:31 a.m.");
                                break;
                            case "7th Ave and 26th St":
                                mTimesList.add("6:46 a.m.");
                                mTimesList.add("7:42 a.m.");
                                mTimesList.add("8:42 a.m.");
                                mTimesList.add("9:42 a.m.");
                                mTimesList.add("10:42 a.m.");
                                mTimesList.add("11:42 a.m.");
                                mTimesList.add("12:42 p.m.");
                                mTimesList.add("1:42 p.m.");
                                mTimesList.add("2:42 p.m.");
                                mTimesList.add("2:58 p.m.");
                                mTimesList.add("3:42 p.m.");
                                mTimesList.add("4:42 p.m.");
                                mTimesList.add("5:42 p.m.");
                                mTimesList.add("6:42 p.m.");
                                mTimesList.add("6:58 p.m.");
                                mTimesList.add("7:42 p.m.");
                                mTimesList.add("9:01 p.m.");
                                mTimesList.add("11:02 p.m.");
                                mTimesList.add("12:37 a.m.");
                                break;
                            case "Laidley Transit Mall":
                                mTimesList.add("7:00 a.m.");
                                mTimesList.add("8:00 a.m.");
                                mTimesList.add("9:00 a.m.");
                                mTimesList.add("10:00 a.m.");
                                mTimesList.add("11:00 a.m.");
                                mTimesList.add("12:00 p.m.");
                                mTimesList.add("1:00 p.m.");
                                mTimesList.add("2:00 p.m.");
                                mTimesList.add("3:00 p.m.");
                                mTimesList.add("3:15 p.m.");
                                mTimesList.add("4:00 p.m.");
                                mTimesList.add("5:00 p.m.");
                                mTimesList.add("6:00 p.m.");
                                mTimesList.add("7:00 p.m.");
                                mTimesList.add("7:15 p.m.");
                                mTimesList.add("8:00 p.m.");
                                mTimesList.add("9:15 p.m.");
                                mTimesList.add("11:15 p.m.");
                                mTimesList.add("-");
                                break;
                            case "Capitol Complex":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                        }
                        break;
                }
                break;
            case "Sunday":
                switch (mDirection) {
                    case "Outbound":
                        switch (mTimepoint) {
                            case "Capitol Complex":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                            case "Laidley Transit Mall":
                                mTimesList.add("-");
                                mTimesList.add("6:30 a.m.");
                                mTimesList.add("8:30 a.m.");
                                mTimesList.add("10:00 a.m.");
                                mTimesList.add("11:15 a.m.");
                                mTimesList.add("12:00 p.m.");
                                mTimesList.add("2:30 p.m.");
                                mTimesList.add("3:30 p.m.");
                                mTimesList.add("5:25 p.m.");
                                mTimesList.add("7:15 p.m.");
                                mTimesList.add("9:15 p.m.");
                                mTimesList.add("11:15 p.m.");
                                break;
                            case "7th Ave and 26th St":
                                mTimesList.add("4:55 a.m.");
                                mTimesList.add("6:40 a.m.");
                                mTimesList.add("8:40 a.m.");
                                mTimesList.add("10:10 a.m.");
                                mTimesList.add("11:25 a.m.");
                                mTimesList.add("12:10 p.m.");
                                mTimesList.add("2:40 p.m.");
                                mTimesList.add("3:40 p.m.");
                                mTimesList.add("5:35 p.m.");
                                mTimesList.add("7:25 p.m.");
                                mTimesList.add("9:25 p.m.");
                                mTimesList.add("11:25 p.m.");
                                break;
                            case "12th and Dunbar Ave":
                                mTimesList.add("5:02 a.m.");
                                mTimesList.add("6:47 a.m.");
                                mTimesList.add("8:47 a.m.");
                                mTimesList.add("10:17 a.m.");
                                mTimesList.add("11:35 a.m.");
                                mTimesList.add("12:17 p.m.");
                                mTimesList.add("2:47 p.m.");
                                mTimesList.add("3:47 p.m.");
                                mTimesList.add("5:43 p.m.");
                                mTimesList.add("7:33 p.m.");
                                mTimesList.add("9:33 p.m.");
                                mTimesList.add("11:33 p.m.");
                                break;
                            case "WV State University":
                                mTimesList.add("5:10 a.m.");
                                mTimesList.add("6:55 a.m.");
                                mTimesList.add("8:55 a.m.");
                                mTimesList.add("10:25 a.m.");
                                mTimesList.add("11:43 a.m.");
                                mTimesList.add("12:25 p.m.");
                                mTimesList.add("2:55 p.m.");
                                mTimesList.add("3:55 p.m.");
                                mTimesList.add("5:51 p.m.");
                                mTimesList.add("7:41 p.m.");
                                mTimesList.add("9:41 p.m.");
                                mTimesList.add("11:41 p.m.");
                                break;
                            case "St Albans Station":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("10:36 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("3:07 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                            case "40th St and Route 25":
                                mTimesList.add("5:18 a.m.");
                                mTimesList.add("7:11 a.m.");
                                mTimesList.add("9:11 a.m.");
                                mTimesList.add("10:47 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("12:41 p.m.");
                                mTimesList.add("3:19 p.m.");
                                mTimesList.add("4:11 p.m.");
                                mTimesList.add("6:07 p.m.");
                                mTimesList.add("7:57 p.m.");
                                mTimesList.add("9:57 p.m.");
                                mTimesList.add("11:57 p.m.");
                                break;
                            case "Nitro Marketplace":
                                mTimesList.add("5:28 a.m.");
                                mTimesList.add("7:21 a.m.");
                                mTimesList.add("9:21 a.m.");
                                mTimesList.add("10:57 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("12:51 p.m.");
                                mTimesList.add("3:29 p.m.");
                                mTimesList.add("4:21 p.m.");
                                mTimesList.add("6:17 p.m.");
                                mTimesList.add("8:07 p.m.");
                                mTimesList.add("10:06 p.m.");
                                mTimesList.add("12:07 a.m.");
                                break;
                            case "Mardi Gras Casino & Resort":
                                mTimesList.add("-");
                                mTimesList.add("7:25 a.m.");
                                mTimesList.add("9:25 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("3:33 p.m.");
                                mTimesList.add("4:25 p.m.");
                                mTimesList.add("6:20 p.m.");
                                mTimesList.add("8:10 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("12:10 a.m.");
                                break;
                        }
                        break;
                    case "Inbound":
                        switch (mTimepoint) {
                            case "Mardi Gras Casino & Resort":
                                mTimesList.add("-");
                                mTimesList.add("7:45 a.m.");
                                mTimesList.add("9:25 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("4:13 p.m.");
                                mTimesList.add("6:20 p.m.");
                                mTimesList.add("8:24 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("12:10 a.m.");
                                break;
                            case "Nitro Marketplace":
                                mTimesList.add("5:30 a.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("11:03 a.m.");
                                mTimesList.add("1:13 p.m.");
                                mTimesList.add("4:18 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("10:21 p.m.");
                                mTimesList.add("-");
                                break;
                            case "40th St and Route 25":
                                mTimesList.add("5:40 a.m.");
                                mTimesList.add("7:55 a.m.");
                                mTimesList.add("9:35 a.m.");
                                mTimesList.add("11:13 a.m.");
                                mTimesList.add("1:23 p.m.");
                                mTimesList.add("4:28 p.m.");
                                mTimesList.add("6:30 p.m.");
                                mTimesList.add("8:34 p.m.");
                                mTimesList.add("10:31 p.m.");
                                mTimesList.add("12:20 a.m.");
                                break;
                            case "St Albans Station":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("4:40 p.m.");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                            case "WV State University":
                                mTimesList.add("5:57 a.m.");
                                mTimesList.add("8:12 a.m.");
                                mTimesList.add("9:52 a.m.");
                                mTimesList.add("11:29 a.m.");
                                mTimesList.add("1:40 p.m.");
                                mTimesList.add("4:52 p.m.");
                                mTimesList.add("6:47 p.m.");
                                mTimesList.add("8:48 p.m.");
                                mTimesList.add("10:47 p.m.");
                                mTimesList.add("12:35 a.m.");
                                break;
                            case "12th and Dunbar Ave":
                                mTimesList.add("6:05 a.m.");
                                mTimesList.add("8:20 a.m.");
                                mTimesList.add("10:02 a.m.");
                                mTimesList.add("11:37 a.m.");
                                mTimesList.add("1:50 p.m.");
                                mTimesList.add("5:00 p.m.");
                                mTimesList.add("6:55 p.m.");
                                mTimesList.add("8:56 p.m.");
                                mTimesList.add("10:55 p.m.");
                                mTimesList.add("12:42 a.m.");
                                break;
                            case "7th Ave and 26th St":
                                mTimesList.add("6:15 a.m.");
                                mTimesList.add("8:28 a.m.");
                                mTimesList.add("10:12 a.m.");
                                mTimesList.add("11:45 a.m.");
                                mTimesList.add("2:00 p.m.");
                                mTimesList.add("5:10 p.m.");
                                mTimesList.add("7:03 p.m.");
                                mTimesList.add("9:03 p.m.");
                                mTimesList.add("11:03 p.m.");
                                mTimesList.add("12:49 a.m.");
                                break;
                            case "Laidley Transit Mall":
                                mTimesList.add("6:30 a.m.");
                                mTimesList.add("8:40 a.m.");
                                mTimesList.add("10:27 a.m.");
                                mTimesList.add("12:00 p.m.");
                                mTimesList.add("2:15 p.m.");
                                mTimesList.add("5:25 p.m.");
                                mTimesList.add("7:15 p.m.");
                                mTimesList.add("9:13 p.m.");
                                mTimesList.add("11:15 p.m.");
                                mTimesList.add("-");
                                break;
                            case "Capitol Complex":
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                mTimesList.add("-");
                                break;
                        }
                        break;
                }
                break;
        }

        String[] mTimes = new String[mTimesList.size()];

        for (int i = 0; i < mTimes.length; i++)
            mTimes[i] = mTimesList.get(i);

        return mTimes;
    }

}
